name: ds_envs
channels:
  - defaults
dependencies:
  - python=3.8.5
  - pip
  - pip:
        - data-science-types==0.2.19
        - numpy==1.18.5
        - pandas==1.1.3
        - matplotlib==3.3.2
        - tensorflow==2.3.1
        - tensorflow-probability==0.11.1
        - azureml-sdk==1.16.0
        - mlflow==1.11.0
        - azureml-mlflow==1.16.0
        - debugpy==1.0.0
