[tool.poetry]
name = "ds_envs"
version = "2020.10.03"
description = "Data science environments"
authors = ["Mads Ehrhorn <meh@venzonxt.com>"]

[tool.poetry.dependencies]
python = "3.8.5"
plotly = "*"
streamlit = "*"
azure-common = "*"
azure-mgmt-resource = "*"
azure-storage-blob = "*"
azure-cli-core = "*"
azure-identity = "*"
adal = "*"
msrestazure = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.1.0"]
build-backend = "poetry.masonry.api"
